#!/bin/sh

# Function to execute commands in sequence
execute_commands() {
    nx run react-ui-lib-ai-ideas:lint || exit 1
    nx run react-ui-lib-ai-ideas:test || exit 1
    nx run react-ui-lib-ai-ideas:build || exit 1
    nx run nextapp-ai-ideas:lint || exit 1
    nx run nextapp-ai-ideas:test || exit 1
    nx run nextapp-ai-ideas:build || exit 1
    nx run nextapp-ai-ideas-e2e:lint || exit 1
    nx run nextapp-ai-ideas-e2e:e2e || exit 1
}

# Execute commands
execute_commands